name: Remove stale branches

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  remove-stale-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove stale branches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/stale-branches.sh
